apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi-app
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - image: fastapi-app:latest
        name: fastapi-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
