apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-app
    namespace: default
  name: fastapi-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    protocol: TCP
    name: http
    targetPort: 8000
  selector:
    app: fastapi-app
