"""
End-to-end Locust load test for the FastAPI social app.

Accounts are seeded SEPARATELY (run seed_accounts.py once first). This file
does NOT create users — each simulated user picks a RANDOM account from
accounts.csv, logs in once on start, then loops the authenticated endpoints:
feed listing, search, single-post reads, post create/update/delete, and votes.

Run against the port-forwarded service:
    kubectl port-forward svc/fastapi-app 5000:5000
    locust -f locustfile.py --host http://localhost:5000

Headless example (2 min, 50 users, spawn 5/s), writing CSV stats:
    locust -f locustfile.py --host http://localhost:5000 \
        --headless -u 50 -r 5 -t 2m --csv results/run
"""

import csv
import random
from pathlib import Path

from locust import HttpUser, task, between


# --- Load seeded accounts from CSV (login only — no creation here) ----------
ACCOUNTS_PATH = Path(__file__).parent / "accounts.csv"

with ACCOUNTS_PATH.open(newline="") as f:
    ACCOUNTS = list(csv.DictReader(f))

if not ACCOUNTS:
    raise RuntimeError(f"No accounts found in {ACCOUNTS_PATH} — run seed_accounts.py first")


class SocialAppUser(HttpUser):
    # Think-time between tasks: 1-3s, models a real user browsing.
    wait_time = between(1, 3)

    def on_start(self):
        """Runs once per simulated user: pick a RANDOM seeded account and log
        in. No signup — accounts must already exist (seed_accounts.py)."""
        self.account = random.choice(ACCOUNTS)
        self.token = None
        self.created_post_ids = []
        self._login()

    def _login(self):
        """OAuth2PasswordRequestForm expects FORM data with fields
        'username' and 'password' — NOT json. username carries the email."""
        with self.client.post(
            "/login",
            data={"username": self.account["email"], "password": self.account["password"]},
            name="/login",
            catch_response=True,
        ) as resp:
            if resp.status_code == 200:
                self.token = resp.json().get("access_token")
                resp.success()
            else:
                resp.failure(f"login failed {resp.status_code}: {resp.text[:200]}")

    @property
    def auth_headers(self):
        return {"Authorization": f"Bearer {self.token}"} if self.token else {}

    # --- read tasks (heaviest weight — reads dominate real traffic) ---------
    @task(10)
    def list_feed(self):
        self.client.get(
            "/posts/",
            params={"limit": 10, "skip": 0},
            headers=self.auth_headers,
            name="/posts/ [feed]",
        )

    @task(5)
    def search_feed(self):
        self.client.get(
            "/posts/",
            params={"limit": 10, "search": random.choice(["a", "e", "load", "test", ""])},
            headers=self.auth_headers,
            name="/posts/ [search]",
        )

    @task(4)
    def read_single_post(self):
        """Read a post this user created; skip if none yet."""
        if not self.created_post_ids:
            return
        post_id = random.choice(self.created_post_ids)
        with self.client.get(
            f"/posts/{post_id}",
            headers=self.auth_headers,
            name="/posts/{id} [read]",
            catch_response=True,
        ) as resp:
            if resp.status_code in (200, 403, 404):
                resp.success()
            else:
                resp.failure(f"read post {resp.status_code}")

    @task(3)
    def read_user(self):
        """Exercises the public /users/{id} read path. 404 tolerated."""
        with self.client.get(
            f"/users/{random.randint(1, len(ACCOUNTS))}",
            name="/users/{id}",
            catch_response=True,
        ) as resp:
            if resp.status_code in (200, 403, 404):
                resp.success()
            else:
                resp.failure(f"get user {resp.status_code}")

    # --- write tasks (lower weight — writes are rarer than reads) -----------
    @task(3)
    def create_post(self):
        with self.client.post(
            "/posts/",
            json={
                "title": f"load post {random.randint(1, 1_000_000)}",
                "content": "generated by locust e2e load test",
                "published": True,
            },
            headers=self.auth_headers,
            name="/posts/ [create]",
            catch_response=True,
        ) as resp:
            if resp.status_code == 201:
                pid = resp.json().get("post_id")
                if pid is not None:
                    self.created_post_ids.append(pid)
                resp.success()
            elif resp.status_code == 401:
                resp.failure("create post unauthorized — token missing/expired")
            else:
                resp.failure(f"create post {resp.status_code}")

    @task(2)
    def update_post(self):
        if not self.created_post_ids:
            return
        post_id = random.choice(self.created_post_ids)
        with self.client.put(
            f"/posts/{post_id}",
            json={
                "title": f"updated {random.randint(1, 1_000_000)}",
                "content": "updated by locust",
                "published": True,
            },
            headers=self.auth_headers,
            name="/posts/{id} [update]",
            catch_response=True,
        ) as resp:
            if resp.status_code in (200, 403, 404):
                resp.success()
            else:
                resp.failure(f"update post {resp.status_code}")

    @task(2)
    def vote_post(self):
        """Like/unlike a post, tolerating 409 (already voted) and 404
        (post gone) — expected business responses under concurrent load."""
        if not self.created_post_ids:
            return
        post_id = random.choice(self.created_post_ids)
        with self.client.post(
            "/vote/",
            json={"post_id": post_id, "dir": random.choice([0, 1])},
            headers=self.auth_headers,
            name="/vote/",
            catch_response=True,
        ) as resp:
            if resp.status_code in (201, 403, 404, 409):
                resp.success()
            else:
                resp.failure(f"vote {resp.status_code}")

    @task(1)
    def delete_post(self):
        """Clean up one of our own posts to avoid unbounded growth."""
        if not self.created_post_ids:
            return
        post_id = self.created_post_ids.pop()
        with self.client.delete(
            f"/posts/{post_id}",
            headers=self.auth_headers,
            name="/posts/{id} [delete]",
            catch_response=True,
        ) as resp:
            if resp.status_code in (204, 403, 404):
                resp.success()
            else:
                resp.failure(f"delete post {resp.status_code}")